### ISSUE TITLE
VirtualROMObject.csがコミットされていません。

### ISSUE THREAD

**Issue by etpop** [otakuto/TomatoTool#1]
VirtualROMObject.csがコミットされていません。

TomatoTool.csprojの287行目にて以下の記述があります。
------
    <Compile Include="VirtualROMObject.cs" />
------

**Comment by otakuto** [comment]
これでどうでしょうか?
b405bc1ebe8e99bf65cf5b6961b07beb657444d9

**Comment by etpop** [comment]
動きました。
ありがとうございます(._.)
